//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeminSpectrumAnalyser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>*RST</string>
  <string>(SET DefaultTimeout to 2000)</string>
  <string>:FORMat:TRACe:DATA ASC,8</string>
  <string>:FORMat:BORDer SWAPped</string>
  <string>:INSTrument:SELect SA</string>
  <string>:CONFigure:SANalyzer</string>
  <string>:DISPlay:WINDow:TRACe:Y:SCALe:RLEVel -30</string>
  <string>:SENSe:AVERage:COUNt 5</string>
  <string>:DISPlay:WINDow:TRACe:Y:SCALe:PDIVision 7</string>
  <string>:INITiate:CONTinuous 0</string>
  <string>:TRACe1:TYPE WRITe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection COMMANDRST {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["COMMANDRST"]));
            }
            set {
                this["COMMANDRST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ADDRESS1 {
            get {
                return ((string)(this["ADDRESS1"]));
            }
            set {
                this["ADDRESS1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PORT1 {
            get {
                return ((int)(this["PORT1"]));
            }
            set {
                this["PORT1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ADDRESS2 {
            get {
                return ((string)(this["ADDRESS2"]));
            }
            set {
                this["ADDRESS2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PORT2 {
            get {
                return ((int)(this["PORT2"]));
            }
            set {
                this["PORT2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double MAGIC {
            get {
                return ((double)(this["MAGIC"]));
            }
            set {
                this["MAGIC"] = value;
            }
        }
    }
}
